name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: [ "main" ]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run PR agent on PRs and respond to comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        with:
          config-path: .github/pr-agent-config.yaml
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
